stages:
  - build
  - deploy
  - mirror

# Specify tags if needed
variables:
  DOCKER_DRIVER: overlay2

# Job for building the React application
build:
  stage: build
  image: node:14
  script:
    - apk update
    - apk add git
    - npm install
    - npm run build
    - mv ./build public
  only:
    - main
  tags:
    - docker

# Job for deploying the built application to GitLab Pages
pages:
  stage: deploy
  script:
    - echo "Deploying to GitLab Pages"
  artifacts:
    paths:
      - public
  only:
    - main
  tags:
    - docker

# Job for mirroring to GitHub
mirror_to_github:
  stage: mirror
  script:
    - apk update
    - apk add git
    - git remote set-url github https://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/jasonsimpson2024/Final_Year_project_Github.git
    - git push github HEAD:main
  only:
    - main
  tags:
    - docker
