stages:
  - build
  - deploy
  - mirror  # Added a new stage for mirroring to GitHub

# Specify tags if needed
variables:
  DOCKER_DRIVER: overlay2
  GITHUB_PAT: $GITHUB_ACCESS_TOKEN  # Use an environment variable to store your GitHub PAT

# Job for building the React application
build:
  stage: build
  image: node:14  # Use a Node.js image with Node.js 14
  script:
    - npm install  # Install project dependencies
    - npm run build  # Build the React application
    - mv ./build public  # Rename the 'build' directory to 'public' (required for GitLab Pages)
  only:
    - main
  tags:
    - docker

# Job for deploying the built application to GitLab Pages
pages:
  stage: deploy
  script:
    - echo "Deploying to GitLab Pages"
  artifacts:
    paths:
      - public  # This path should match the directory name from the deployment script
  only:
    - main
  tags:
    - docker

# Job for mirroring to GitHub
mirror_to_github:
  stage: mirror
  script:
    - apk update
    - apk add git
    - export GITHUB_TOKEN="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"
    - git remote add github https://$GITHUB_TOKEN@github.com/jasonsimpson2024/Final_Year_project_Github.git
    - git push github HEAD:main

  only:
    - main
  tags:
    - docker
