stages:
  - build
  - deploy
  - mirror  # Added a new stage for mirroring to GitHub

# Specify tags if needed
variables:
  DOCKER_DRIVER: overlay2  # Use an environment variable to store your GitHub PAT

# Job for building the React application
build:
  stage: build
  image: node:14-alpine  # Use an Alpine Linux-based Node.js image
  script:
    - npm install  # Install project dependencies
    - npm run build  # Build the React application
    - mv ./build public  # Rename the 'build' directory to 'public' (required for GitLab Pages)
  only:
    - main
  tags:
    - docker

# Job for deploying the built application to GitLab Pages
pages:
  stage: deploy
  script:
    - echo "Deploying to GitLab Pages"
  artifacts:
    paths:
      - public  # This path should match the directory name from the deployment script
  only:
    - main
  tags:
    - docker

# Job for mirroring to GitHub
mirror_to_github:
  stage: mirror
  image: alpine:latest  # Switched to an Alpine Linux-based image
  script:
    - apk update
    - apk add git
    - git remote set-url github https://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/jasonsimpson2024/Final_Year_project_Github.git
    - git push github HEAD:main
  only:
    - main
  tags:
    - docker
